

"""
Django settings for pythonprojectapis project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv
import dj_database_url


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

# Loads variables from .env during local development
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set")


# ============================================================
# DEBUG
# ============================================================

DEBUG = os.getenv("DEBUG", "False").lower() == "true"


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1"
    ).split(",")
    if host.strip()
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "django_filters",

    # Cloudinary
    "cloudinary",
    "cloudinary_storage",

    # Local apps
    "base.apps.BaseConfig",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Serve static files in production
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "pythonprojectapis.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI APPLICATION
# ============================================================

WSGI_APPLICATION = "pythonprojectapis.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = os.getenv("DATABASE_URL")


if DATABASE_URL:
    # Production database - PostgreSQL
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:
    # Local development database - SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


    # ============================================================
    # PASSWORD VALIDATION
    # ============================================================

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": (
                "django.contrib.auth.password_validation."
                "UserAttributeSimilarityValidator"
            ),
        },
        {
            "NAME": (
                "django.contrib.auth.password_validation."
                "MinimumLengthValidator"
            ),
        },
        {
            "NAME": (
                "django.contrib.auth.password_validation."
                "CommonPasswordValidator"
            ),
        },
        {
            "NAME": (
                "django.contrib.auth.password_validation."
                "NumericPasswordValidator"
            ),
        },
    ]


    # ============================================================
    # INTERNATIONALIZATION
    # ============================================================

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True


    # ============================================================
    # STATIC FILES
    # ============================================================

    STATIC_URL = "/static/"

    STATIC_ROOT = BASE_DIR / "staticfiles"


    # ============================================================
    # MEDIA / CLOUDINARY
    # ============================================================

    DEFAULT_FILE_STORAGE = (
        "cloudinary_storage.storage.MediaCloudinaryStorage"
    )

    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
        "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
        "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
    }


    # ============================================================
    # EMAIL
    # ============================================================

    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


    # ============================================================
    # DJANGO REST FRAMEWORK
    # ============================================================

    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ),

        "DEFAULT_PERMISSION_CLASSES": (
            "rest_framework.permissions.IsAuthenticated",
        ),

        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.UserRateThrottle",
            "rest_framework.throttling.AnonRateThrottle",
        ],

        "DEFAULT_THROTTLE_RATES": {
            "user": "100/day",
            "anon": "10/day",
            "product_create": "10/min",
        },

        "DEFAULT_FILTER_BACKENDS": [
            "django_filters.rest_framework.DjangoFilterBackend",
        ],
    }


    # ============================================================
    # JWT CONFIGURATION
    # ============================================================

    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),

        "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

        "AUTH_HEADER_TYPES": ("Bearer",),
    }


    # ============================================================
    # RAZORPAY
    # ============================================================

    RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")

    RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")


    # ============================================================
    # PRODUCTION SECURITY
    # ============================================================

    if not DEBUG:

        SECURE_PROXY_SSL_HEADER = (
            "HTTP_X_FORWARDED_PROTO",
            "https",
        )

        SESSION_COOKIE_SECURE = True

        CSRF_COOKIE_SECURE = True

        SECURE_SSL_REDIRECT = True

        SECURE_HSTS_SECONDS = 31536000

        SECURE_HSTS_INCLUDE_SUBDOMAINS = True

        SECURE_HSTS_PRELOAD = True


        # ============================================================
        # DEFAULT PRIMARY KEY
        # ============================================================

        DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"